# typed: false
# frozen_string_literal: true

# This formula is auto-generated by scripts/update-homebrew.sh — do not edit manually.
# The url fields are filled with GitHub's own asset download URLs (copied
# verbatim from the release API), because the CLI's release tag
# (@tigrisdata/cli@<version>) contains '/' and '@' and is not safe to
# hand-assemble into a path.
class Tigris < Formula
  desc "Command line interface for Tigris object storage"
  homepage "https://www.tigrisdata.com"
  license "MIT"
  version "VERSION_PLACEHOLDER"

  on_macos do
    on_arm do
      url "URL_DARWIN_ARM64_PLACEHOLDER"
      sha256 "SHA_DARWIN_ARM64_PLACEHOLDER"
    end
    on_intel do
      url "URL_DARWIN_X64_PLACEHOLDER"
      sha256 "SHA_DARWIN_X64_PLACEHOLDER"
    end
  end

  on_linux do
    on_arm do
      url "URL_LINUX_ARM64_PLACEHOLDER"
      sha256 "SHA_LINUX_ARM64_PLACEHOLDER"
    end
    on_intel do
      url "URL_LINUX_X64_PLACEHOLDER"
      sha256 "SHA_LINUX_X64_PLACEHOLDER"
    end
  end

  def install
    host_os = OS.mac? ? "darwin" : "linux"
    host_arch = Hardware::CPU.arm? ? "arm64" : "x64"
    bin.install "tigris-#{host_os}-#{host_arch}" => "tigris"
    bin.install_symlink "tigris" => "t3"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tigris --version")
  end
end
